# Generated by Django 5.1.4 on 2024-12-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficviolation',
            name='id',
        ),
        migrations.AlterField(
            model_name='trafficviolation',
            name='violation_time',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
