# Generated by Django 5.1.4 on 2024-12-10 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_trafficviolation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficviolation',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.ownerinfo'),
        ),
    ]
